fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "kuynerok@gmail.com"
        sender_name: Vadym
    use_flash_notifications: false